// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class Feuil1
{
    public int Id { get; set; }

    public string Champ1 { get; set; }
}