// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcMachine
{
    /// <summary>
    /// ID de la machine
    /// </summary>
    public int Idmachine { get; set; }

    /// <summary>
    /// ID du Client
    /// </summary>
    public int? LnkIdclient { get; set; }

    /// <summary>
    /// N° de série machine
    /// </summary>
    public string StrMachineSn { get; set; }

    /// <summary>
    /// Nom client final
    /// </summary>
    public string StrMachineClientName { get; set; }

    /// <summary>
    /// Nom du fournisseur de la machine
    /// </summary>
    public string StrMachineFournisseurName { get; set; }

    /// <summary>
    /// Lieu d&apos;installation de la machine sur le site client
    /// </summary>
    public string StrMachineSite { get; set; }

    /// <summary>
    /// Machine vendue / démo / pret / location / etc...
    /// </summary>
    public string StrMachineTransaction { get; set; }

    /// <summary>
    /// Type de la machine : DV-EVT-2100, ICM-D2P-....
    /// </summary>
    public string StrMachineModele { get; set; }

    /// <summary>
    /// Complément d&apos;informations sur le type de la machine
    /// </summary>
    public string StrMachineModeleComplement { get; set; }

    /// <summary>
    /// Options logicielles actives
    /// </summary>
    public string StrMachineOptionSw { get; set; }

    /// <summary>
    /// Options matérielles (standards)
    /// </summary>
    public string StrMachineOptionHw { get; set; }

    /// <summary>
    /// Options matérielles (non standards)
    /// </summary>
    public string StrMachineConfigHwspec { get; set; }

    /// <summary>
    /// Remarques importantes sur la machine
    /// </summary>
    public string StrMachineWarning { get; set; }

    /// <summary>
    /// Date de la commande de la machine
    /// </summary>
    public DateTime? DateMachineCommande { get; set; }

    /// <summary>
    /// Date de la revue de contrat
    /// </summary>
    public DateTime? DateMachineRevueContrat { get; set; }

    /// <summary>
    /// Date de livraison demandée
    /// </summary>
    public DateTime? DateMachineLivDemande { get; set; }

    /// <summary>
    /// Date de livraison programmée
    /// </summary>
    public DateTime? DateMachineLivProgramme { get; set; }

    /// <summary>
    /// Date du contrôle final (mise à dispo machine)
    /// </summary>
    public DateTime? DateMachineCtrlFinal { get; set; }

    /// <summary>
    /// Date de livraison effective
    /// </summary>
    public DateTime? DateMachineLivraison { get; set; }

    /// <summary>
    /// Fin de garantie
    /// </summary>
    public DateTime? DateMachineFinGarantie { get; set; }

    /// <summary>
    /// Date du dernier retrofit
    /// </summary>
    public DateTime? DateMachineRetrofit { get; set; }

    /// <summary>
    /// Machine hors service
    /// </summary>
    public bool? BMachineHorsService { get; set; }

    /// <summary>
    /// Machine rétrofité
    /// </summary>
    public bool? BMachineRetrofit { get; set; }

    /// <summary>
    /// Débridage logiciel
    /// </summary>
    public bool? BMachineDebridageSoft { get; set; }

    /// <summary>
    /// Date fin bridage logiciel
    /// </summary>
    public DateTime? DateMachineDateMaxUseSoft { get; set; }

    /// <summary>
    /// Machine etalonnable
    /// </summary>
    public bool? BMachineEtalonnable { get; set; }

    /// <summary>
    /// Dossier machine (papier, st&amp;c) soldé
    /// </summary>
    public bool? MachineSuiviEtatSolde { get; set; }

    /// <summary>
    /// Etat de la machine : prod, stock, livré, ...
    /// </summary>
    public string MachineSuiviEtat { get; set; }

    /// <summary>
    /// Causes liées aux retards de livraison
    /// </summary>
    public string StrCauseRetard { get; set; }

    /// <summary>
    /// Etat du dossier &apos;papier&apos; bleu : Inexistant, en cours, etc.
    /// </summary>
    public string MachineSuiviDossier { get; set; }

    /// <summary>
    /// Archivage SolidWorks
    /// </summary>
    public byte? MachineSuiviSldwks { get; set; }

    /// <summary>
    /// Commentaires divers (période de calibration, client relancé,...)
    /// </summary>
    public string StrMachineCommentaire { get; set; }

    public short? PeriodeCalibration { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcClient LnkIdclientNavigation { get; set; }

    public virtual ICollection<TblTcDefautProduction> TblTcDefautProduction { get; } = new List<TblTcDefautProduction>();

    public virtual ICollection<TblTcFicheIntervention> TblTcFicheIntervention { get; } = new List<TblTcFicheIntervention>();

    public virtual ICollection<TblTcInterventionClient> TblTcInterventionClient { get; } = new List<TblTcInterventionClient>();

    public virtual ICollection<TblTcLogiciel> TblTcLogiciel { get; } = new List<TblTcLogiciel>();

    public virtual ICollection<TblTcProduit> TblTcProduit { get; } = new List<TblTcProduit>();
}