// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcContact
{
    public int Idpersonne { get; set; }

    public int? LnkIdclient { get; set; }

    public string StrPersNom { get; set; }

    public string StrPersPrenom { get; set; }

    public string StrPersTitre { get; set; }

    public string StrPersFonction { get; set; }

    public string StrPersTel { get; set; }

    public string StrPersFax { get; set; }

    public string StrPersEmail { get; set; }

    public bool? BPersInactif { get; set; }

    public bool? BPersPrincipal { get; set; }

    /// <summary>
    /// Contact client transférable vers PMI
    /// </summary>
    public bool? BPersTranfertPmi { get; set; }

    /// <summary>
    /// Contact vérifié par le SAV
    /// </summary>
    public bool? BpersFait { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcClient LnkIdclientNavigation { get; set; }

    public virtual ICollection<TblTcFicheIntervention> TblTcFicheIntervention { get; } = new List<TblTcFicheIntervention>();
}