// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcTypeIntervention
{
    public int IdtypeIntervention { get; set; }

    public string StrTypeInterventionDescription { get; set; }

    public virtual ICollection<TblTcInterventionClient> TblTcInterventionClient { get; } = new List<TblTcInterventionClient>();
}