// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcTypeAction
{
    public int IdtypeAction { get; set; }

    public string StrTypeActionDescription { get; set; }

    public virtual ICollection<TblTcSsIntervertion> TblTcSsIntervertion { get; } = new List<TblTcSsIntervertion>();
}