// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcEtatFicheIntervention
{
    public int IdetatFicheIntervention { get; set; }

    public string StrEfidescription { get; set; }

    public string StrEfiaide { get; set; }

    public int? NEfiordre { get; set; }

    public virtual ICollection<TblTcFicheIntervention> TblTcFicheIntervention { get; } = new List<TblTcFicheIntervention>();
}