// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcEtalon
{
    /// <summary>
    /// ID de l&apos;étalon
    /// </summary>
    public int Idetalon { get; set; }

    /// <summary>
    /// N° d&apos;ordre
    /// </summary>
    public short? IEtalonOrdre { get; set; }

    /// <summary>
    /// N° de série  de l&apos;étalon (Product SN)
    /// </summary>
    public string StrEtalonSn { get; set; }

    /// <summary>
    /// Nom de l&apos;etalon (Product ID)
    /// </summary>
    public string StrEtalonNom { get; set; }

    /// <summary>
    /// Type de l&apos;étalon (Informations)
    /// </summary>
    public string StrEtalonType { get; set; }

    /// <summary>
    /// Date du certificat
    /// </summary>
    public DateTime DateEtalonCe { get; set; }

    /// <summary>
    /// Numéro certificat d&apos;etalonnage
    /// </summary>
    public string StrNumeroCe { get; set; }

    /// <summary>
    /// Commentaire
    /// </summary>
    public string MemoEtalonCommentaire { get; set; }

    /// <summary>
    /// Periodicité d&apos;etalonnage en mois
    /// </summary>
    public short? NPeriodiciteMois { get; set; }

    /// <summary>
    /// Etalon actif
    /// </summary>
    public bool BEtalonActif { get; set; }

    public byte[] SsmaTimeStamp { get; set; }
}