// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcFicheIntervention
{
    /// <summary>
    /// ID De la fiche d&apos;intervention
    /// </summary>
    public int IdficheIntervention { get; set; }

    /// <summary>
    /// ID Client à laquelle est liée la fiche
    /// </summary>
    public int? LnkIdclient { get; set; }

    /// <summary>
    /// ID Machine à laquelle est liée la fiche (optionnel)
    /// </summary>
    public int? LnkIdmachine { get; set; }

    /// <summary>
    /// ID Personne (appelant) à laquelle est liée la fiche (optionnel)
    /// </summary>
    public int? LnkIdpersonne { get; set; }

    /// <summary>
    /// ID Etat de la fiche
    /// </summary>
    public int? LnkIdetatFicheIntervention { get; set; }

    /// <summary>
    /// ID du type d&apos;intervention de la fiche
    /// </summary>
    public int? LnkIdtypeFicheIntervention { get; set; }

    /// <summary>
    /// Date de création
    /// </summary>
    public DateTime? DateFicreation { get; set; }

    /// <summary>
    /// Date d&apos;ouverture
    /// </summary>
    public DateTime? DateFiouverture { get; set; }

    /// <summary>
    /// ID de l&apos;intervenant d&apos;ouverture
    /// </summary>
    public int? LnkIdintervenantO { get; set; }

    /// <summary>
    /// Date de fermeure
    /// </summary>
    public DateTime? DateFifermeture { get; set; }

    /// <summary>
    /// ID de l&apos;intervenant d&apos;ouverture
    /// </summary>
    public int? LnkIdintervenantF { get; set; }

    /// <summary>
    /// Tel de l&apos;appelant
    /// </summary>
    public string StrFitelephoneAppelant { get; set; }

    /// <summary>
    /// Email de l&apos;appelant
    /// </summary>
    public string StrFiemailAppelant { get; set; }

    /// <summary>
    /// Titre de la fiche
    /// </summary>
    public string MemFititre { get; set; }

    /// <summary>
    /// Description du problème / de la demande / etc.
    /// </summary>
    public string MemFidescription { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcClient LnkIdclientNavigation { get; set; }

    public virtual TblTcEtatFicheIntervention LnkIdetatFicheInterventionNavigation { get; set; }

    public virtual TblTcIntervenant LnkIdintervenantFNavigation { get; set; }

    public virtual TblTcIntervenant LnkIdintervenantONavigation { get; set; }

    public virtual TblTcMachine LnkIdmachineNavigation { get; set; }

    public virtual TblTcContact LnkIdpersonneNavigation { get; set; }

    public virtual TblTcTypeFicheIntervention LnkIdtypeFicheInterventionNavigation { get; set; }

    public virtual ICollection<TTempsPassé> TTempsPassé { get; } = new List<TTempsPassé>();

    public virtual ICollection<TblTcSsIntervertion> TblTcSsIntervertion { get; } = new List<TblTcSsIntervertion>();
}