// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcLogiciel
{
    public int Idlogiciel { get; set; }

    public int? LnkIdmachine { get; set; }

    public int? LnkIdtypeLogiciel { get; set; }

    /// <summary>
    /// Langue du logiciel
    /// </summary>
    public string StrLogLangue { get; set; }

    public string StrLogTypeLogicielComplement { get; set; }

    public string StrLogVersion { get; set; }

    public string StrLogVersionComplement { get; set; }

    public string StrLogSn { get; set; }

    public DateTime DateLogMaj { get; set; }

    public bool? BLogActif { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcMachine LnkIdmachineNavigation { get; set; }

    public virtual TblTcTypeLogiciel LnkIdtypeLogicielNavigation { get; set; }
}