// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcTypeContrat
{
    /// <summary>
    /// Index
    /// </summary>
    public int IdtypeContrat { get; set; }

    public int? ITypContratOrder { get; set; }

    /// <summary>
    /// Definition du modèle de contrat texte court
    /// </summary>
    public string StrTypContratModelDefShort { get; set; }

    /// <summary>
    /// Definition du modèle de contrat texte long
    /// </summary>
    public string StrTypContratModelDefLong { get; set; }

    public string StrTypContratPays { get; set; }

    public int? NTypContratDelaiInterv { get; set; }

    public int? NTypContratDelaiExpPiece { get; set; }

    /// <summary>
    ///  Intervention sur site sous 48H appel avant 12H00
    /// </summary>
    public bool? BTypContratGarantieDep { get; set; }

    /// <summary>
    ///  Envoi de pièces de rechange sous 48H appel avant 12H00
    /// </summary>
    public bool? BTypContratGarantieExpPiece { get; set; }

    /// <summary>
    /// Garantie Hot Line (limite de temps et du nombre d&apos;appels)
    /// </summary>
    public bool? BTypContratGarantieHotLine { get; set; }

    /// <summary>
    ///  Visite annuelle HORS CALIBRAGE une fois par an (Avec déplacement en supplément)
    /// </summary>
    public bool? BTypContratGarantie1VisiteAn { get; set; }

    /// <summary>
    ///  Visite annuelle AVEC CALIBRAGE une fois par an  (Avec déplacement en supplément)
    /// </summary>
    public bool? BTypContratGarantie1CalibrageAn { get; set; }

    /// <summary>
    ///  Déplacement en supplément
    /// </summary>
    public bool? BTypContratGarantieDepSupp { get; set; }

    /// <summary>
    ///  Main d&apos;oeuvre gratuite
    /// </summary>
    public bool? BTypContratGarantieMo { get; set; }

    /// <summary>
    ///  Petite fourniture gratuite
    /// </summary>
    public bool? BTypContratGarantiePetitePiece { get; set; }

    /// <summary>
    ///  Mise à jour logicielle gratuite  (Dans la limite des capacités du matériel)
    /// </summary>
    public bool? BTypContratGarantieSoft { get; set; }

    /// <summary>
    /// Toutes pieces gratuites
    /// </summary>
    public bool? BTypContratGarantieToutePiece { get; set; }

    /// <summary>
    /// Contrat renouvelable par tacite reconduction
    /// </summary>
    public bool? BTypContratRenouvelableAuto { get; set; }

    /// <summary>
    /// Frais de déplacement pour le calibrage  intégré dans le prix du contrat
    /// </summary>
    public bool? BTypContratFraisDep1CalibrageAn { get; set; }

    /// <summary>
    /// Commentaire
    /// </summary>
    public string StrTypContratComment { get; set; }

    /// <summary>
    /// Contrat actif oui/non
    /// </summary>
    public bool? BTypContratActif { get; set; }

    public byte[] SsmaTimeStamp { get; set; }
}