// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcContrat
{
    /// <summary>
    /// Index
    /// </summary>
    public int Idcontrat { get; set; }

    /// <summary>
    /// Index du numéro de machine
    /// </summary>
    public int? LnkIdmachine { get; set; }

    /// <summary>
    /// Index code client
    /// </summary>
    public int? LnkIdclient { get; set; }

    /// <summary>
    /// Index du type contrat
    /// </summary>
    public int? LnkIdtypeContrat { get; set; }

    /// <summary>
    /// Numero du contrat
    /// </summary>
    public string StrContratNumero { get; set; }

    /// <summary>
    /// Index d&apos;année (1 pour la 1ere année, 2 pour la 2nde, etc.)
    /// </summary>
    public string StrContratIndex { get; set; }

    /// <summary>
    /// Date de debut de contrat
    /// </summary>
    public DateTime? DateContratDebut { get; set; }

    /// <summary>
    /// Date d&apos;échéance du contrat
    /// </summary>
    public DateTime? DateContratFin { get; set; }

    /// <summary>
    /// N° de la commande associé au contrat
    /// </summary>
    public string StrContratNumCommande { get; set; }

    /// <summary>
    /// Prix du contrat en Euro (signe sur contrat)
    /// </summary>
    public string StrContratPrix { get; set; }

    /// <summary>
    /// Distance en kilomètres (Aller retour) Site Delta / Site Client
    /// </summary>
    public string StrContratDistanceKmsAr { get; set; }

    /// <summary>
    /// Prix du déplacement en Euro (signe sur contrat)
    /// </summary>
    public string StrContratCoutDep { get; set; }

    /// <summary>
    /// Unite de 15mn (nomalement 15 unite par contrat)
    /// </summary>
    public string StrContratNbreUniteHotLine { get; set; }

    /// <summary>
    /// Nombre de minutes par unité
    /// </summary>
    public string StrContrattempMinuteUnite { get; set; }

    /// <summary>
    /// Nombre de minutes créditée par le contrat
    /// </summary>
    public string StrContrattempMinuteCredit { get; set; }

    /// <summary>
    /// Nombre de minutes débitée
    /// </summary>
    public string StrContrattempMinuteDebit { get; set; }

    /// <summary>
    /// Contrat actif/inactif
    /// </summary>
    public bool? BContratActif { get; set; }

    /// <summary>
    /// Commentaire
    /// </summary>
    public string MemoContratComment { get; set; }

    public byte[] SsmaTimeStamp { get; set; }
}