// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcTypeProduit
{
    public int IdtypeProduit { get; set; }

    public string StrTypProdCodeArticle { get; set; }

    public string StrTypProdDesignation { get; set; }

    public short? NTypProdOrdre { get; set; }

    public bool? BTypProdObsolete { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual ICollection<TblTcProduit> TblTcProduit { get; } = new List<TblTcProduit>();
}