// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcSsIntervertion
{
    /// <summary>
    /// ID de l&apos;action
    /// </summary>
    public int IdssIntervention { get; set; }

    /// <summary>
    /// ID de l&apos;intervention auquelle est raccroché l&apos;action
    /// </summary>
    public int? LnkIdficheIntervention { get; set; }

    /// <summary>
    /// Type prédéfini d&apos;action
    /// </summary>
    public int? LnkIdtypeAction { get; set; }

    /// <summary>
    /// Intervenant affecté à l&apos;action
    /// </summary>
    public int? LnkIdintervenantAct { get; set; }

    /// <summary>
    /// Echeance
    /// </summary>
    public DateTime? DataSsInterventionEcheance { get; set; }

    /// <summary>
    /// Descriptif ou complément d&apos;informations sur l&apos;action à apporter
    /// </summary>
    public string StrSsInterventionAction { get; set; }

    /// <summary>
    /// Date de réalisation de l&apos;action
    /// </summary>
    public DateTime? DateSsIntervention { get; set; }

    /// <summary>
    /// Temps passé lors de l&apos;action
    /// </summary>
    public int? LSsInterventionTpasseMin { get; set; }

    /// <summary>
    /// Réponse apportée
    /// </summary>
    public string StrSsInterventionCorrectif { get; set; }

    /// <summary>
    /// Action soldé oui / non
    /// </summary>
    public bool? BActionSoldee { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcFicheIntervention LnkIdficheInterventionNavigation { get; set; }

    public virtual TblTcIntervenant LnkIdintervenantActNavigation { get; set; }

    public virtual TblTcTypeAction LnkIdtypeActionNavigation { get; set; }
}