// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcProduit
{
    public int Idproduit { get; set; }

    public int LnkIdmachine { get; set; }

    public int? LnkIdtypeProduit { get; set; }

    public string StrProdSn { get; set; }

    public string StrProdRevision { get; set; }

    public string StrProdMarque { get; set; }

    public string StrProdCommentaire { get; set; }

    public string StrProdAffectation { get; set; }

    public DateTime DateProdLivraison { get; set; }

    public bool? BProdActif { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual TblTcMachine LnkIdmachineNavigation { get; set; }

    public virtual TblTcTypeProduit LnkIdtypeProduitNavigation { get; set; }
}