// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcTypeLogiciel
{
    public int IdtypeLogiciel { get; set; }

    public string Designation { get; set; }

    public string Categorie { get; set; }

    public short? Ordre { get; set; }

    public bool? Obsolete { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual ICollection<TblTcLogiciel> TblTcLogiciel { get; } = new List<TblTcLogiciel>();
}