// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

[Serializable]
public partial class TblTcClient
{
    /// <summary>
    /// ID du client
    /// </summary>
    public int Idclient { get; set; }

    /// <summary>
    /// Code compta CIEL
    /// </summary>
    public string StrClCodeGescom { get; set; }

    public int? StrClCodePmi { get; set; }

    /// <summary>
    /// Client mort
    /// </summary>
    public bool? BClDesactive { get; set; }

    /// <summary>
    /// Client transférable vers PMI
    /// </summary>
    public string StrClTransfertPmi { get; set; }

    /// <summary>
    /// Client transféré dans PMI
    /// </summary>
    public bool? BClTransfertOk { get; set; }

    /// <summary>
    /// Dernière mise à jour de la fiche client
    /// </summary>
    public DateTime? DateClMajFiche { get; set; }

    /// <summary>
    /// Nom de la société
    /// </summary>
    public string StrClLivSociete { get; set; }

    /// <summary>
    /// Nom du revendeur
    /// </summary>
    public string StrClRevendeur { get; set; }

    /// <summary>
    /// Adresse 1
    /// </summary>
    public string StrClLivAdr1 { get; set; }

    /// <summary>
    /// Adresse 2
    /// </summary>
    public string StrClLivAdr2 { get; set; }

    /// <summary>
    /// Adresse 3
    /// </summary>
    public string StrClLivAdr3 { get; set; }

    /// <summary>
    /// Adresse / CP
    /// </summary>
    public string StrClLivCodePostal { get; set; }

    /// <summary>
    /// Adresse / Ville
    /// </summary>
    public string StrClLivVille { get; set; }

    /// <summary>
    /// Adresse / Pays
    /// </summary>
    public string StrClLivPays { get; set; }

    /// <summary>
    /// Tel. de la société
    /// </summary>
    public string StrClTel { get; set; }

    /// <summary>
    /// Email de la société
    /// </summary>
    public string StrEmail { get; set; }

    /// <summary>
    /// Site web de la société
    /// </summary>
    public string LhtClWeb { get; set; }

    /// <summary>
    /// Secteur d&apos;activité de la société
    /// </summary>
    public string StrClActivite { get; set; }

    /// <summary>
    /// Type métier de la société
    /// </summary>
    public string StrClMetier { get; set; }

    /// <summary>
    /// Types de produits
    /// </summary>
    public string StrClProduits { get; set; }

    /// <summary>
    /// Origine du contact
    /// </summary>
    public string StrClOrigineContact { get; set; }

    /// <summary>
    /// Remarques / infos sur la société
    /// </summary>
    public string StrClInfo { get; set; }

    public short? NClPriorite { get; set; }

    public string StrClPriorite { get; set; }

    public DateTime? DateClCreationFiche { get; set; }

    /// <summary>
    /// Date du 1er contact commercial
    /// </summary>
    public DateTime? DateClPremierContact { get; set; }

    /// <summary>
    /// Date du dernier contact commercial
    /// </summary>
    public DateTime? DateClDernierContact { get; set; }

    public string StrClStatutCommercial { get; set; }

    public string StrClStatutClient { get; set; }

    /// <summary>
    /// Distance en km de louviers à la société
    /// </summary>
    public short? NClKm { get; set; }

    /// <summary>
    /// Fax. de la société
    /// </summary>
    public string StrClFax { get; set; }

    /// <summary>
    /// ID (lien) du revendeur
    /// </summary>
    public int? LnkIdrevendeur { get; set; }

    /// <summary>
    /// Nom court de la société
    /// </summary>
    public string StrNomCourt { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual ICollection<TblTcContact> TblTcContact { get; } = new List<TblTcContact>();

    public virtual ICollection<TblTcFicheIntervention> TblTcFicheIntervention { get; } = new List<TblTcFicheIntervention>();

    public virtual ICollection<TblTcInterventionClient> TblTcInterventionClient { get; } = new List<TblTcInterventionClient>();

    public virtual ICollection<TblTcMachine> TblTcMachine { get; } = new List<TblTcMachine>();
}