// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TblTcPeriodeCalibration
{
    public int N { get; set; }

    public int? Champ1 { get; set; }
}