// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class TTempsPassé
{
    public int IdtempsPasse { get; set; }

    public int? LnkIdficheIntervention { get; set; }

    public int? LnkIdintervenant { get; set; }

    public DateTime DateTpasse { get; set; }

    public string StrTpassePersonne { get; set; }

    public int NTpasseMinute { get; set; }

    public virtual TblTcFicheIntervention LnkIdficheInterventionNavigation { get; set; }
}