// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepApiTraining.Models;

public partial class UsysApplicationLog
{
    public int Id { get; set; }

    public string SourceObject { get; set; }

    public string DataMacroInstanceId { get; set; }

    public int? ErrorNumber { get; set; }

    public string Category { get; set; }

    public string ObjectType { get; set; }

    public string Description { get; set; }

    public string Context { get; set; }

    public DateTime? Created { get; set; }

    public byte[] SsmaTimeStamp { get; set; }
}